// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0YEhxTd9qgphANCOOs3FSuNzcO9mqg74',
    appId: '1:1021003208948:web:b96f918b781d5f8f02a6a1',
    messagingSenderId: '1021003208948',
    projectId: 'bookquizapp',
    authDomain: 'bookquizapp.firebaseapp.com',
    storageBucket: 'bookquizapp.appspot.com',
    measurementId: 'G-M409LZF2W7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLHgrQH6U_-kTCJj4a2NyZa384pAghFUY',
    appId: '1:1021003208948:android:96e45340266b294402a6a1',
    messagingSenderId: '1021003208948',
    projectId: 'bookquizapp',
    storageBucket: 'bookquizapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGzPd2JuGaBVvW-5lKhl_-q8YUJRI-AwA',
    appId: '1:1021003208948:ios:88bcd541d773035d02a6a1',
    messagingSenderId: '1021003208948',
    projectId: 'bookquizapp',
    storageBucket: 'bookquizapp.appspot.com',
    iosBundleId: 'app.quiz.book',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGzPd2JuGaBVvW-5lKhl_-q8YUJRI-AwA',
    appId: '1:1021003208948:ios:09bac74904e7bc9102a6a1',
    messagingSenderId: '1021003208948',
    projectId: 'bookquizapp',
    storageBucket: 'bookquizapp.appspot.com',
    iosBundleId: 'app.quiz.book.RunnerTests',
  );
}
